### ISSUE TITLE
notebook not found as module when using python 3 in notebook

### ISSUE THREAD

**Issue by apache8080** [acm-uiuc/gpu-cluster-backend#7]
https://github.com/acm-uiuc/gpu-cluster-backend/blob/9dcca39d62e1d494c65744820d01cb5d14b37686/app.py#L39

When it tries to run the script using python3 it can't find the module notebook but when just using python it runs fine. Any thoughts on what the best way to fix this is?

**Comment by narendasan** [comment]
@apache8080 which container are you trying to launch?

**Comment by apache8080** [comment]
@narendasan Caffe

**Comment by narendasan** [comment]
Caffe is not setup at all, its just the standard nvcaffe container from Nvidia.  I am not sure what we should do about it since I don't think most people use Python with Caffe1.

**Comment by narendasan** [comment]
But yeah it works with python and not python3 because python3 is not installed in the container

**Comment by apache8080** [comment]
My bad I meant Caffe2, Yeah I guess we can just update the Dockerfile.
