### ISSUE TITLE
Create a way to deliver users a host to ssh into 

### ISSUE THREAD

**Issue by narendasan** [acm-uiuc/gpu-cluster-backend#8]
Not all frameworks work directly with jupyter, it might make sense to open the ssh port and return a host in that case.

**Comment by narendasan** [comment]
We may also want to open the ssh port on all images

**Comment by apache8080** [comment]
Do we still want to do this?

**Comment by narendasan** [comment]
I think this is less important than other features, id leave it until we see typical use cases
